### PR TITLE
Better organized screenshots and added screenshot-2 to readme.md.

### PR DESCRIPTION
**Pull request by jorgesumle**
When merged, readme.md will look like the image attached.
captura de pantalla de 2016-08-04 03 35 11

### CODE REVIEW

**Comment by jorgesumle** [comment]
It would also be nice to use a .gif with all screenshots, but I prefer it simple.

**Comment by aramk** [comment]
Thanks, I think this might affect the Wordpress readme which expects the shortcuts in the old location?

**Comment by jorgesumle** [comment]
Sorry I don't understand, what do you mean by shortcuts, it's only an image. Anyway, I think that the screenshots should be in a file called screenshots, not in the root directory, I find it quite messy. I don't see any problem with that. These images are just a demo, no?
captura de pantalla de 2016-08-09 01 43 32

**Comment by aramk** [comment]
Screenshots are under "== Screenshots ==" but that's fine, I'll sort it out when publishing. Thanks!

**Pull request merged**
