### PR TITLE
Remove parsing plugin data hack

### PR DESCRIPTION
**Pull request by rob006**
This fix issue with broken WordPress smart quotes functionality. By default WP convert `"` into typography quotes, so for polish language `Lorem ipsum "dolor sit amet"` become `Lorem ipsum „dolor sit amet”`. Loading `wp-admin/includes/plugin.php` break this - WP converts `"` into english quotes: `Lorem ipsum “dolor sit amet”`, which is incorrect for polish language.

Also, parsing plugin data in this way is a really dirty hack, which could break site when WP team move `get_plugin_data` function into other file - we should really avoid such solutions.

### CODE REVIEW

**Comment by aramk** [comment]
Thanks for that. Could you please explain how parsing the settings may cause the smart quotes to break?

**Comment by rob006** [comment]
`get_plugin_data()` by default use `_get_plugin_data_markup_translate()`, which use `wptexturize()`, which has note: 
> Do not use this function before the 'init' action hook; everything will break.

**Comment by aramk** [comment]
Does 4bfa8ff fix your issue? I moved the logic for getting the plugin data to run after the `init` action and this seems to still work.

**Comment by rob006** [comment]
It works, but it still a hack and still has incorrect plugin release date. If you really want get plugin version/author/etc from file header, you should use `get_file_data()`. But still only useful thing is version - author and URL is basically static and can be hardcoded. You can not calculate release date by `mtime()`, because you get plugin instalation/update date instead real release date, so you probably need put this date in code and change on every release.

**Comment by aramk** [comment]
Hmm yeah, that's a good point. I'll go with your change then. Thanks!

**Pull request merged**
