### PR TITLE
Fabric Engine KL Language

### PR DESCRIPTION
**Pull request by AndrewHazelden**
Added a Fabric Engine KL Language module. 

The KL language works at this point but I've had to comment out the "RESERVED  \b(?alt:reserved.txt)\b" line as it seems Crayon can't load an external resource that is 33 KB in size.

### CODE REVIEW

**Comment by aramk** [comment]
Thanks, feel free to also add the language and credit in readme.txt

**Comment by AndrewHazelden** [comment]
aramk, is there a limit for the number of line entries in a single text resource file for a Crayon language module?

**Comment by aramk** [comment]
Hi Andrew,
There's no explicit limit, but very long files will increase the time taken
to render.

**Comment by AndrewHazelden** [comment]
Thanks for the suggestion. I've updated the readme file.

The new KL module works fine as is but I'd like to get the full RESERVED keywords text file active if possible.

I was wondering if you could try the new KL language module on your system and let me know if the example Crayon KL language snippet `/util/sample/kl.txt` has syntax highlighting that still works fine when the RESERVED keyword line is uncommented in the main `langs/kl/kl.txt` file. 

Specifically, I am curious to find out if the loading issue I had on my wordpress site with the full length reserved.txt definitions active is related to a Wordpress/PHP/Javascript thing on my end, or due to an implementation issue in my language file.

What happens on my blog is that if I have the full 33KB size reserved.txt file loaded in the language modules's kl.txt file, the syntax highlighted portion of the text in a new blog post doesn't seem to be applied or visible and appears as a single line entry.

When I delete about 1/3rd of the entries from the reserved.txt file to shrink the file size a bit it seems to work fine and the issue goes away.

I'd really appreciate hearing any insight you might have on this issue as I'm a bit puzzled by it.

**Here are a few screenshots to show you what I mean:**

This is a test blog post made using the current version of the KL module I have posted on GitHub that has the RESERVED keyword commented out in the main language .txt file. (Everything seems to work fine):
kl syntax with reserved commented out

This is what happens when I uncomment the `kl.txt `RESERVED keyword line. When I reload the webpage the syntax code block disappears in Wordpress and only a single line entry is shown:
kl syntax with full size reserved uncommented

Then if I manually deleted half of the text in the `reserved.txt` file and refresh the webpage, the syntax highlighting works again:
kl syntax with half size reserved uncommented

**Pull request merged**
